---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
inputs:
- name: alpine_curl_sources
- name: version
outputs:
- name: artifact
run:
  path: sh
  args:
  - -exc
  - |
    # Do your build steps here. Creating temporary file below as a sample:
    export CURRENT_TIMESTAMP=$(date +"%Y%m%d%H%S")
    export CURRENT_VERSION=$(cat version/version)
    # Creating sample package file with a file name containing the new version number
    tar -zcvf cloud_foundry_demo-$CURRENT_TIMESTAMP-$CURRENT_VERSION.tar.gz app_sources_production
    cp cloud_foundry_demo-$CURRENT_TIMESTAMP-$CURRENT_VERSION.tar.gz artifact
